name: molecule e2e

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'requirementsDocs.txt'
    - '.devcontainer'


jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.8.5]
    steps:
     - uses: actions/checkout@v2.4.0

     - uses: actions/setup-python@v2
       with:
         python-version: "${{ matrix.python-version }}"
         architecture: 'x64'

     - uses: nolte/molecule-action@fix/downgread-molecule
       with:
         molecule_working_dir: "/home/runner/work/ansible-role-mcrcon/ansible-role-mcrcon" #${{env.GITHUB_REPOSITORY}}
