name: molecule e2e

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'requirementsDocs.txt'
    - '.devcontainer'


jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.8.5]
    steps:
     - uses: actions/checkout@v3.1.0

     - uses: actions/setup-python@v3
       with:
         python-version: "${{ matrix.python-version }}"
         architecture: 'x64'

     - uses: gofrolist/molecule-action@v2.2.17
